<?php
    return [
        'admin' => [
            'create-language', // table langauges
            'read-language',
            'update-language',
            'delete-language',
            'show-language',
            'create-city', // table cities
            'read-city',
            'update-city',
            'delete-city',
            'show-city',
            'create-country', // table countries
            'read-country',
            'update-country',
            'delete-country',
            'show-country',
            'create-zipcode', // table zipcodes
            'read-zipcode',
            'update-zipcode',
            'delete-zipcode',
            'show-zipcode',
            'create-tag', // table tags
            'read-tag',
            'update-tag',
            'delete-tag',
            'show-tag',
            'create-pricing-plan', // table pricing_plans
            'read-pricing-plan',
            'update-pricing-plan',
            'delete-pricing-plan',
            'show-pricing-plan',
            'create-user', // table users
            'read-user',
            'update-user',
            'delete-user',
            'show-user',
            'create-detail', // table details
            'read-detail',
            'update-detail',
            'delete-detail',
            'show-detail',
            'create-course', // table courses
            'read-course',
            'update-course',
            'delete-course',
            'show-course',
            'create-level', // table levels
            'read-level',
            'update-level',
            'delete-level',
            'show-level',
            'create-subject', // table subjects
            'read-subject',
            'update-subject',
            'delete-subject',
            'show-subject',
            'create-book', // table books
            'read-book',
            'update-book',
            'delete-book',
            'show-book',
            'create-chapter', // table chapters
            'read-chapter',
            'update-chapter',
            'delete-chapter',
            'show-chapter',
            'create-page', // table pages
            'read-page',
            'update-page',
            'delete-page',
            'show-page',
            'create-user-detail', // table user-details
            'read-user-detail',
            'update-user-detail',
            'delete-user-detail',
            'show-user-detail',
            'create-user-meta', // table user-metas
            'read-user-meta',
            'update-user-meta',
            'delete-user-meta',
            'show-user-meta',
            'create-course-user', // table course-users
            'read-course-user',
            'update-course-user',
            'delete-course-user',
            'show-course-user',
            'create-school', // table schools
            'read-school',
            'update-school',
            'delete-school',
            'show-school',
            'create-class', // table classs
            'read-class',
            'update-class',
            'delete-class',
            'show-class',
            'create-state', // table states
            'read-state',
            'update-state',
            'delete-state',
            'show-state',
            'create-organization', // table organizations
            'read-organization',
            'update-organization',
            'delete-organization',
            'show-organization',
            'create-department', // table departments
            'read-department',
            'update-department',
            'delete-department',
            'show-department',
            'create-notification', // table notifications
            'read-notification',
            'update-notification',
            'delete-notification',
            'show-notification',
            'create-lms-event', // table lms-events
            'read-lms-event',
            'update-lms-event',
            'delete-lms-event',
            'show-lms-event',
            'create-user-payment', // table user-payments
            'read-user-payment',
            'update-user-payment',
            'delete-user-payment',
            'show-user-payment',
            'create-user-subscription', // table user-subscriptions
            'read-user-subscription',
            'update-user-subscription',
            'delete-user-subscription',
            'show-user-subscription',
            'create-payment-transaction', // table payment-transactions
            'read-payment-transaction',
            'update-payment-transaction',
            'delete-payment-transaction',
            'show-payment-transaction',
            'create-quizz', // table quizzs
            'read-quizz',
            'update-quizz',
            'delete-quizz',
            'show-quizz',
            'create-quiz-detail', // table quiz-details
            'read-quiz-detail',
            'update-quiz-detail',
            'delete-quiz-detail',
            'show-quiz-detail',
            'create-question', // table questions
            'read-question',
            'update-question',
            'delete-question',
            'show-question',
            'create-question-detail', // table question-details
            'read-question-detail',
            'update-question-detail',
            'delete-question-detail',
            'show-question-detail',
            'create-quiz-question', // table quiz-questions
            'read-quiz-question',
            'update-quiz-question',
            'delete-quiz-question',
            'show-quiz-question',
            'create-response', // table responses
            'read-response',
            'update-response',
            'delete-response',
            'show-response',
            'create-response-detail', // table response-details
            'read-response-detail',
            'update-response-detail',
            'delete-response-detail',
            'show-response-detail',
            'create-user-quizz', // table user-quizzs
            'read-user-quizz',
            'update-user-quizz',
            'delete-user-quizz',
            'show-user-quizz',
            'create-user-quiz-detail', // table user-quiz-details
            'read-user-quiz-detail',
            'update-user-quiz-detail',
            'delete-user-quiz-detail',
            'show-user-quiz-detail',
            'create-user-response', // table user-responses
            'read-user-response',
            'update-user-response',
            'delete-user-response',
            'show-user-response',
            'create-quiz-leaderboard', // table quiz-leaderboards
            'read-quiz-leaderboard',
            'update-quiz-leaderboard',
            'delete-quiz-leaderboard',
            'show-quiz-leaderboard',
            'read-teams', // table teams
            'create-team',
            'update-team',
            'delete-team',
            'show-team',
            'read-team-users', // team users table
            'add-team-user',
            'delete-team-user',
            'create-org', // table orgs
            'read-org',
            'update-org',
            'delete-org',
            'show-org',
            'create-dept', // table depts
            'read-dept',
            'update-dept',
            'delete-dept',
            'show-dept',
            'read-plans',
            'create-plan',
            'show-plan',
            'update-plan',
            'delete-plan',
            'create-team-process',
            'read-team-process',
            'update-team-process',
            'delete-team-process',
            'show-team-process',
            'read-process',
            'create-process',
            'delete-process',
            'update-process',
            'show-process',
            'read-department-users',
            'create-department-users',
            'delete-department-users',
            'read-step',
            'create-step',
            'update-step',
            'show-step',
            'delete-step',
            'read-process-instance',
            'create-process-instance',
            'update-process-instance',
            'show-process-instance',
            'delete-process-instance',
            'read-step-instance',
            'update-step-instance',
            'delete-step-instance',
            'show-step-instance'
        ],
        'author' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'reviewer' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'sponsor' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'student' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'parent' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
    ];
